name: Docker build

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_TAG=$(echo '${{ github.event.pull_request.title }}' | tr ' ' '-' | tr '/' '-')
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker build -t practice-image:${IMAGE_TAG} .

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: practice-image:${{ env.IMAGE_TAG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
